"""RiskReport: the final, consolidated output of the Risk/Report Agent.

Combines every specialist agent's report (zoning, litigation, document
analysis, and any future ones) with an overall score from RiskScorer and
the mandatory disclaimer (CLAUDE.md hard guardrail #3). This is the one
artifact meant to actually reach a buyer -- specialist reports stay
internal/intermediate, so only this schema carries the disclaimer.
"""

from datetime import datetime
from typing import Self

from pydantic import BaseModel, Field, computed_field, model_validator

from bhoomicheck.schemas.parcel import ParcelIdentifier
from bhoomicheck.schemas.report import BaseAgentReport
from bhoomicheck.schemas.scoring import ScoredFinding

DISCLAIMER = (
    "This report is generated by an automated due-diligence tool based on "
    "publicly available records, which may be incomplete, outdated, or "
    "contain errors. It does not constitute legal advice, and does not "
    "guarantee clear title or freedom from encumbrances. Consult a "
    "licensed advocate before making any purchase decision based on this "
    "report."
)


class RiskReport(BaseModel):
    """The final report a buyer actually reads.

    Attributes:
        parcel: The parcel this report is about.
        generated_at: When this consolidated report was assembled.
        overall_score: 0-100 from RiskScorer, 100 = no issues found across
            every specialist report.
        scored_findings: Every finding that fed the score, with which
            rule fired for each -- the audit trail behind overall_score.
        specialist_reports: Every specialist report this was built from.
            Typed as the shared base contract (architecture principle 1)
            so this schema needs no change when a new specialist agent
            (land records, owner background, growth potential) is added.
    """

    parcel: ParcelIdentifier
    generated_at: datetime
    overall_score: int = Field(ge=0, le=100)
    scored_findings: list[ScoredFinding]
    specialist_reports: list[BaseAgentReport] = Field(min_length=1)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def disclaimer(self) -> str:
        """The mandatory disclaimer (CLAUDE.md hard guardrail #3).

        A computed field, not a regular one with a default: that makes it
        impossible to construct a RiskReport with different disclaimer
        text, even by accident, while still serializing into
        model_dump()/model_dump_json() output like any other field.
        """
        return DISCLAIMER

    @model_validator(mode="after")
    def require_matching_parcel(self) -> Self:
        # A final report silently mixing findings from two different
        # parcels would be a serious, hard-to-notice bug -- reject it here.
        mismatched = [
            r.agent_name for r in self.specialist_reports if r.parcel != self.parcel
        ]
        if mismatched:
            raise ValueError(
                f"specialist report(s) {mismatched} have a different "
                "parcel than this RiskReport's parcel"
            )
        return self
